from __future__ import annotations

import argparse
import json
from pathlib import Path


def fmt(v) -> str:
    if v is None:
        return "-"
    if isinstance(v, float):
        return f"{v:.2f}"
    return str(v)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True, help="Input JSONL results file")
    ap.add_argument("--out", dest="outp", required=True, help="Output .tex file (table rows)")
    args = ap.parse_args()

    inp = Path(args.inp)
    outp = Path(args.outp)
    rows = []
    for line in inp.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        scenario = r.get("mode", "?")
        nacts = (r.get("instance") or {}).get("activities", "?")
        mode = r.get("room_mode", "?")
        cp_sec = r.get("cp_seconds", None)
        pen0 = r.get("penalty_base", None)
        pen1 = r.get("penalty_ls", None)
        rows.append((scenario, nacts, mode, cp_sec, pen0, pen1))

    lines = [
        "% Auto-generated by scripts/jsonl_to_latex_table.py",
        "% Scenario & #Acts & Mode & CP time (s) & Penalty (base) & Penalty (LS)",
    ]
    for (scenario, nacts, mode, cp_sec, pen0, pen1) in rows:
        mode = str(mode).replace("_", "\\_")
        scenario = str(scenario).replace("_", "\\_")
        lines.append(f"{scenario} & {nacts} & {mode} & {fmt(cp_sec)} & {fmt(pen0)} & {fmt(pen1)} \\\\")

    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

