from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import median


def _fmt_float(v: float) -> str:
    return f"{v:.2f}"


def _escape_latex(value: object) -> str:
    return str(value).replace("_", "\\_")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True, help="Input JSONL results file")
    ap.add_argument("--out", dest="outp", required=True, help="Output .tex file (table rows)")
    args = ap.parse_args()

    rows: list[dict] = []
    for line in Path(args.inp).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("penalty_base") is None or row.get("penalty_ls") is None:
            continue
        rows.append(row)

    grouped: dict[str, list[dict]] = {}
    for row in rows:
        scenario = str(row.get("mode", "?"))
        grouped.setdefault(scenario, []).append(row)

    lines = [
        "% Auto-generated by scripts/jsonl_to_latex_ls_table.py",
        "% Scenario & Runs & Median base penalty & Median LS penalty & Median delta & Median improvement (\\%)",
    ]

    for scenario in sorted(grouped.keys()):
        group = grouped[scenario]
        runs = len(group)
        bases = [float(r["penalty_base"]) for r in group]
        lss = [float(r["penalty_ls"]) for r in group]
        deltas = [b - l for b, l in zip(bases, lss)]
        improvements = [((b - l) / b) * 100.0 if b > 0 else 0.0 for b, l in zip(bases, lss)]
        lines.append(
            f"{_escape_latex(scenario)} & {runs} & {_fmt_float(median(bases))}"
            f" & {_fmt_float(median(lss))} & {_fmt_float(median(deltas))} & {_fmt_float(median(improvements))} \\\\"
        )

    outp = Path(args.outp)
    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
