import os

from product.branding import (
    APP_COPYRIGHT_LINE,
    APP_DISPLAY_NAME,
    APP_OWNER_NAME,
    APP_PUBLISHER,
    APP_SHORT_NAME,
    APP_SUBTITLE,
    APP_VERSION,
)

DEFAULT_DAY_START = "08:30"
DEFAULT_SLOT_MINUTES = 90
DEFAULT_BREAK_MINUTES = 0
DEFAULT_TIME_LIMIT = 600
DEFAULT_CP_WORKERS = max(1, min(8, int(os.cpu_count() or 8)))
